name: Publish to Registry
on:    
  release:
      types: [published]
jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '5.0.x'
        - name: Set env
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        - name: Echo Version
          run: |
            echo $RELEASE_VERSION
            echo ${{ env.RELEASE_VERSION }}
        - name: Build the assembly
          run: |
            dotnet build ./src --configuration Release -p:ASM_VER=${{ env.RELEASE_VERSION }}
        - name: Create the package
          run: |
            dotnet pack ./src --configuration Release -p:ASM_VER=${{ env.RELEASE_VERSION }}
        - name: Publish nuget packges version ${{ env.RELEASE_VERSION }}
          run: dotnet nuget push **\*.nupkg -s 'https://nuget.pkg.github.com/imbatony/index.json' -k ${{secrets.NUGET_TOKEN}}